version: "3.8"

services:
  chirpstack:
    image: chirpstack/chirpstack:4
    restart: unless-stopped
    command: -c /etc/chirpstack
    volumes:
      - ./configuration/chirpstack:/etc/chirpstack
    depends_on:
      - postgres
      - redis
      - mosquitto
    ports:
      - "8080:8080"

  chirpstack-gateway-bridge:
    image: chirpstack/chirpstack-gateway-bridge:4
    restart: unless-stopped
    volumes:
      - ./configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
    depends_on:
      - mosquitto
    ports:
      - "1700:1700/udp"

  chirpstack-rest-api:
    image: chirpstack/chirpstack-rest-api:4
    restart: unless-stopped
    command: --server chirpstack:8080 --bind 0.0.0.0:8090 --insecure
    depends_on:
      - chirpstack
    ports:
      - "8090:8090"

  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=chirpstack
      - POSTGRES_USER=chirpstack
      - POSTGRES_DB=chirpstack
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - ./configuration/postgresql/initdb:/docker-entrypoint-initdb.d

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

  mosquitto:
    image: eclipse-mosquitto:2
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - mosquitto_config:/mosquitto/config
      - mosquitto_data:/mosquitto/data

  # --- ioBroker Integration ---
  iobroker:
    image: buanet/iobroker:latest
    container_name: iobroker
    hostname: iobroker
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - iobroker_data:/opt/iobroker
  # ----------------------------

volumes:
  postgresql_data:
  redis_data:
  mosquitto_config:
  mosquitto_data:
  iobroker_data:
