version: '3.9'

services:
  chirpstack:
    image: chirpstack/chirpstack:latest
    container_name: chirpstack
    restart: unless-stopped
    ports:
      - "8080:8080"     # Web-Interface
      - "1700:1700/udp" # UDP für Gateways
    environment:
      - CHIRPSTACK_REGION=EU868
      - TZ=Europe/Berlin
    volumes:
      - ./chirpstack/config:/etc/chirpstack
      - ./chirpstack/data:/var/lib/chirpstack
    depends_on:
      - chirpstack-postgres
      - chirpstack-mqtt

  chirpstack-postgres:
    image: postgres:13
    container_name: chirpstack-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=chirpstack
      - POSTGRES_USER=chirpstack
      - POSTGRES_DB=chirpstack
    volumes:
      - ./chirpstack_db:/var/lib/postgresql/data

  chirpstack-mqtt:
    image: eclipse-mosquitto:2
    container_name: chirpstack-mqtt
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./mqtt/config:/mosquitto/config
      - ./mqtt/data:/mosquitto/data

  iobroker:
    image: buanet/iobroker:latest
    container_name: iobroker
    hostname: iobroker
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - iobrokerdata:/opt/iobroker

volumes:
  iobrokerdata:
